<?php

namespace BackBundle\Repository;

/**
 * ContacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContacterRepository extends \Doctrine\ORM\EntityRepository
{

public function findByMonth($etat,$user)
{
    $emConfig = $this->getEntityManager()->getConfiguration();
    $emConfig->addCustomDatetimeFunction('MONTH', 'DoctrineExtensions\Query\Mysql\Month');
  
    
    $qb = $this->createQueryBuilder('c');
    $qb->select('MONTH(c.datePublication) as mois , count(c) as nbrmission')
       ->where('c.etat = :etat')
       ->andWhere('c.demandeur = :demandeur')
       ->orWhere('c.Annonceur = :annonceur')
       ->groupBy('MONTH(c.datePublication) as mois');
    
    $qb->setParameter('etat', $etat)
       ->setParameter('demandeur', $user)
       ->setParameter('annonceur', $user);
    
    $missions = $qb->getQuery()->getResult();
    return $missions;
}




}
