<?php

namespace BackBundle\Repository;

/**
 * facturationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class facturationRepository extends \Doctrine\ORM\EntityRepository
{
}
